INSERT INTO Label (label_id, label_name, years_active, ceo_name, parent_company, label_country)
VALUES
('LABEL01', 'Columbia Records', '1887-Present', 'Rob Stringer', 'Sony Music', 'US'),
('LABEL02', 'Interscope Records', '1990-Present', 'John Janick', 'Universal Music Group', 'US'),
('LABEL03', 'Warp Records', '1989-Present', 'Steve Beckett', NULL, 'UK'),
('LABEL04', 'Aftermath Entertainment', '1996-Present', 'Dr. Dre', 'Universal Music Group', 'US'),
('LABEL05', 'Zappa Records', '1977-Present', 'Gail Zappa (deceased)', 'UMG (distribution)', 'US'),
('LABEL06', 'Warp Records', '1989-Present', 'Steve Beckett', NULL, 'UK'),
('LABEL07', 'Republic Records', '1995-Present', 'Monte Lipman', 'Universal Music Group', 'US'),
('LABEL08', 'Atlantic Records', '1947-Present', 'Craig Kallman', 'Warner Music Group', 'US'),
('LABEL09', 'XL Recordings', '1989-Present', 'Richard Russell', 'Beggars Group', 'UK'),
('LABEL10', 'Sub Pop', '1986-Present', 'Megan Jasper', 'Warner Music Group (distribution)', 'US'),
('LABEL11', 'Death Row Records', '1991-2006, 2022-Present', 'Snoop Dogg', 'Hasbro (formerly)', 'US'),
('LABEL12', 'Roc-A-Fella Records', '1995-2013', 'Jay-Z', 'Def Jam (distribution)', 'US'),
('LABEL13', 'One Little Independent Records', '1985-Present', 'Derek Birkett', NULL, 'UK'),
('LABEL14', 'XL Recordings', '1989-Present', 'Richard Russell', 'Beggars Group', 'UK'),
('LABEL15', 'RCA Records', '1901-Present', 'Peter Edge', 'Sony Music', 'US'),
('LABEL16', 'Def Jam Recordings', '1984-Present', 'Tunji Balogun', 'Universal Music Group', 'US'),
('LABEL17', 'Astralwerks', '1993-Present', 'Toby Andrews', 'Universal Music Group', 'US'),
('LABEL18', 'Mushroom Records', '1972-1998, 2023-Present', 'Michael Gudinski (deceased)', NULL, 'Australia'),
('LABEL19', 'Warner Bros. Records', '1958-Present', 'Tom Corson', 'Warner Music Group', 'US'),
('LABEL20', 'Geffen Records', '1980-Present', 'Tom March', 'Universal Music Group', 'US'),
('LABEL21', 'Reprise Records', '1960-Present', 'Tom Corson', 'Warner Music Group', 'US'),
('LABEL22', 'Motown Records', '1959-Present', 'Ethiopia Habtemariam', 'Universal Music Group', 'US'),
('LABEL23', '4AD', '1980-Present', 'Simon Halliday', 'Beggars Group', 'UK'),
('LABEL24', 'Parlophone', '1923-Present', 'Mark Mitchell', 'Warner Music Group', 'UK'),
('LABEL25', 'Island Records', '1959-Present', 'Darcus Beese', 'Universal Music Group', 'UK'),
('LABEL26', 'Stones Throw Records', '1996-Present', 'Chris Manak (Peanut Butter Wolf)', NULL, 'US'),
('LABEL27', 'Rough Trade Records', '1978-Present', 'Geoff Travis', 'Beggars Group', 'UK'),
('LABEL28', 'Domino Recording Company', '1993-Present', 'Laurence Bell', NULL, 'UK'),
('LABEL29', 'Rhino Entertainment', '1978-Present', 'Mark Pinkus', 'Warner Music Group', 'US'),
('LABEL30', 'Brainfeeder', '2008-Present', 'Flying Lotus', NULL, 'US');
