INSERT INTO Band (band_id, band_name, bandmember1_name, bandmember2_name, bandmember3_name, bandmember4_name, bandmember5_name, years_active, genre_id, country_of_origin, inspirations, influenced, most_noted_accolade)
VALUES 
('BAND01','Kraftwerk','Florian Schneider','Ralf Hütter','Henning Schmitz','Falk Grieffenhagen', 'Georg Dussick', '1970-present', 'GENRE03', 'Germany', 'The Beatles, Brian Eno', 'Daft Punk, Depeche Mode, Coldplay', 'Grammy Lifetime Achievement Award (2014)'),
('BAND02','Daft Punk','Thomas Bangalter','Guy-Manuel de Homem-Christo',NULL,NULL,NULL,'1993-2021', 'GENRE03', 'France', 'Kraftwerk, Aphex Twin', 'The Weeknd, Kanye West, Pharrell Williams','Grammy Award for Best Dance Recording (2009)'),
('BAND03','Alvvays','Molly Rankin', 'Kenny Hyslop','Alexandra MacPherson','Caitlin Dawson', NULL, '2011-present', 'GENRE04', 'Canada', 'The Smiths, My Bloody Valentine','Phoebe Bridgers, Best Coast','Juno Award for Breakthrough Group of the Year (2015)'),
('BAND04','Animal Collective','Avey Tare','Panda Bear','Geologist','Deakin',NULL,'2000-present', 'GENRE04', 'USA', 'The Beach Boys, Brian Wilson', 'MGMT, Fleet Foxes','Nominated for Grammy Award for Best Alternative Music Album (2009)'),
('BAND05','The Beatles','John Lennon','Paul McCartney','George Harrison','Ringo Starr', NULL, '1960-1970', 'GENRE01', 'UK', 'Buddy Holly, Chuck Berry', 'Oasis, Radiohead, Green Day','Grammy Lifetime Achievement Award (2014)'),
('BAND06','The Beach Boys','Brian Wilson','Mike Love','Carl Wilson','Dennis Wilson', NULL, '1961-present', 'GENRE01', 'USA', 'Chuck Berry, Phil Spector', 'Fleetwood Mac, The Killers','Rock and Roll Hall of Fame (1988)'),
('BAND07','Radiohead','Thom Yorke','Jonny Greenwood','Colin Greenwood','Ed O''Brien', NULL, '1995-present', 'GENRE01', 'UK', 'R.E.M., The Smiths', 'Coldplay, Muse, The 1975','Grammy Award for Best Alternative Music Album (1998)'),
('BAND08','A Tribe Called Quest','Q-Tip','Phife Dawg','Ali Shaheed Muhammad','Jarobi White', NULL, '1985-1998, 2006-2016', 'GENRE02', 'USA','George Clinton, Miles Davis','Kendrick Lamar, Childish Gambino', 'Grammy Award for Best Rap Album (2017)'),
('BAND09','Nine Inch Nails','Trent Reznor','Atticus Ross','Alessandro Cortini', 'Josh Freese', 'Robin Finck', '1988-present','GENRE09','USA','Kraftwerk, David Bowie', 'Marilyn Manson, Linkin Park', 'Grammy Award for Best Metal Performance (1996)'),
('BAND10','System of a Down','Serj Tankian','Daron Malakian','Shavo Odadjian', 'John Dolmayan', NULL, '1994-present', 'GENRE09','USA','Metallica, Slayer','Avenged Sevenfold, Linkin Park', 'Grammy Award for Best Hard Rock Performance (2006)'),
('BAND11','Outkast','André 3000','Big Boi', NULL, NULL, NULL,'1992-present','GENRE02', 'USA', 'George Clinton, Sly Stone', 'Kendrick Lamar, Childish Gambino','Grammy Award for Album of the Year (2004)'),
('BAND12','Death Grips','MC Ride','Zach Hill','Andy Morin', NULL, NULL, '2010-present', 'GENRE08', 'USA', 'Nirvana, The Smashing Pumpkins','JPEGMAFIA, Brockhampton','Nominated for MTV Video Music Award for Best Art Direction (2013)'),
('BAND13','Clipping','Daveed Diggs','William Hutson', 'Jonathan Snipes', NULL, NULL, '2010-present', 'GENRE02', 'USA', 'Kanye West, Death Grips','JPEGMAFIA, Black Midi','Nominated for Hugo Award for Best Dramatic Presentation (2020)'),
('BAND14','Funkadelic','George Clinton','Eddie Hazel', 'Billy Bass Nelson', 'Gary Shider', 'Bernie Worrell', '1968-present','GENRE07','USA','Parliament, Sly and the Family Stone','Prince, Red Hot Chili Peppers', 'Rock and Roll Hall of Fame Inductee (1997)'),
('BAND15','Sonic Youth','Thurston Moore','Kim Gordon', 'Lee Ranaldo', 'Steve Shelley', NULL, '1981-2011', 'GENRE01', 'USA','The Velvet Underground','Nirvana, Radiohead','Rock and Roll Hall of Fame (2018)');
