INSERT INTO Artist (artist_id, artist_name, birth_name, date_of_birth, years_active, genre_id, country_of_origin, inspirations, influenced, most_noted_accolade)
VALUES 
('ARTIST01','David Bowie','David Robert Jones','1947-01-08','1962-2016','GENRE01', 'UK', 'Elvis Presley, Lou Reed, The Beatles, Kraftwerk, Kendrick Lamar', 'Radiohead, Elton John, The Weeknd, Charli XCX', 'Grammy Lifetime Achievement Award (2016)'),
('ARTIST02','Kendrick Lamar','Kendrick Lamar Duckworth','1987-06-17','2003 - Present','GENRE02', 'US', 'Tupac Shakur, Dr. Dre, Prince, Eminem', 'J. Cole, Chance the Rapper, Joey Bada$$', 'Pulitzer Prize for Music (2018) for DAMN.'),
('ARTIST03','Aphex Twin','Richard David James','1971-08-18','1985 - Present','GENRE03', 'Ireland', 'Kraftwerk, Brian Eno', 'Radiohead, Skrillex, deadmau5', 'Grammy Award for Best Dance/Electronic Album (2015) for Syro'),
('ARTIST04','Eminem','Marshall Bruce Mathers III','1972-10-17','1996 - Present','GENRE02', 'US', 'Tupac Shakur, The Notorious B.I.G., Dr. Dre', 'Kendrick Lamar, Logic, J. Cole', 'Academy Award for Best Original Song (2003) for Lose Yourself'),
('ARTIST05','Frank Zappa','Frank Vincent Zappa','1940-12-21','1962 - 1993','GENRE01', 'US', 'Edgard Varèse, Igor Stravinsky', 'Captain Beefheart and His Magic Band, System of a Down, Primus', 'Rock & Roll Hall of Fame Inductee (2017)'),
('ARTIST06','Danny Brown','Daniel Dewan Sewell','1981-03-16','2003 - Present','GENRE02','US','Roy Ayers, A Tribe Called Quest, Eminem, Joy Division','JPEGMAFIA, BROCKHAMPTON, Zelooperz','Libera Award for Best Hip Hop/Rap Album (2020) for U Know What Im Sayin?'),
('ARTIST07','The Weeknd','Abel Makkonen Tesfaye','1990-02-16','2010 - Present','GENRE04', 'Canada', 'Michael Jackson, Prince, Deftones, David Bowie', 'Billie Eilish, Post Malone, Alessia Cara', 'Guinness World Record for Worlds Most Popular Artist (2023)'),
('ARTIST08','Skrillex','Sonny John Moore','1988-01-15','2004 - Present','GENRE03', 'US', 'Aphex Twin, Daft Punk, Kraftwerk', 'Porter Robinson, Fred Again, Zedd', 'Grammy Award for Best Dance Recording (2012) for Scary Monsters and Nice Sprites'),
('ARTIST09','Billie Eilish','Billie Eilish Pirate Baird O''Connell','2001-12-18','2015 - Present','GENRE04', 'US','Tyler, The Creator, Radiohead, Kendrick Lamar, Lana Del Rey','Olivia Rodrigo, Tate McRae', 'Guinness World Record for Youngest Artist to Win All Four Grammy Award General Field Categories (2020)'),
('ARTIST10','Charli XCX','Charlotte Emma Aitchison','1992-08-02','2008 - Present','GENRE04', 'UK', 'David Bowie, Kate Bush, Britney Spears, Björk','SOPHIE, Caroline Polachek, Yaeji', 'Variety Hitmaker Award for Innovation (2020)'),
('ARTIST11','MF DOOM','Dumile Daniel Thompson','1971-01-09','1988 - 2020','GENRE02', 'UK', 'Nas, A Tribe Called Quest, Pete Rock, Madlib','Gorillaz, Tyler, The Creator, Lupe Fiasco', 'MTV Left Field Woodie Award (2007) for Madvillainy'),
('ARTIST12','deadmau5','Joel Thomas Zimmerman','1971-01-08','1998 - Present','GENRE03', 'Canada', 'Aphex Twin, Daft Punk, Kraftwerk, Radiohead','Rezz, Marshmello', 'International Dance Music Award for Best Artist (2010)'),
('ARTIST13','Björk','Björk Guðmundsdóttir','1965-11-21','1977 - Present','GENRE04', 'Iceland', 'Kate Bush, Cocteau Twins, Aphex Twin, Joni Mitchell','Radiohead, Madonna, Charli XCX, Travis Scott', 'Icelandic state Order of the Falcon (1997)'),
('ARTIST14','Miles Davis','Miles Dewey Davis III','1926-05-26','1944 - 1991','GENRE05', 'US','Charlie Parker, Dizzy Gillespie','Herbie Hancock, John Coltrane, Jimi Hendrix', 'Grammy Lifetime Achievement Award (1990)'),
('ARTIST15','Tupac Shakur','Lesane Parish Crooks','1971-09-13','1989 - 1996','GENRE02', 'US', 'Dr. Dre, Public Enemy, George Clinton, Prince','Eminem, Lil Wayne, Kendrick Lamar', 'Rock & Roll Hall of Fame Inductee (2017)');
